CREATE TABLE "Payments" (
	"id"	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	"datetime"	TIMESTAMP NOT NULL,
	"amount"	REAL NOT NULL DEFAULT 0,
	"order_id"	INTEGER NOT NULL,
	"user_id"	INTEGER NOT NULL,
	FOREIGN KEY("user_id") REFERENCES "Users"("id") ON UPDATE CASCADE,
	FOREIGN KEY("order_id") REFERENCES "Orders"("id") ON UPDATE CASCADE
)
